# Generated by Django 4.2.1 on 2023-05-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('iden', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
            ],
        ),
    ]
